name: bip_bech32
version: 0.1.3
author: "BaojunCZ<baojun.cz@gmail.com>"
homepage: https://github.com/OrangeWallet/bech32.git
description: Dart implementing BIP173,Convert fron bitcoinj.
publish_to: https://pub.dartlang.org/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.6.2
